### ISSUE TITLE
Goal Based Reinforcement Learning

### ISSUE THREAD

**Issue by koriavinash1** [deepmind/lab#145]
Is it possible to implement goal based reinforcement learning for any of these 3D environments?

**Comment by tkoeppe** [comment]
You can generally implement whatever you like. DeepMind Lab is merely an environment; what kind of learning you do with it is up to you.

Either way, we have the "nav_maze_random_goal" and "dmlab30/*watermaze*" levels, which may be of interest to you, since they might pose the sort of challenge you're after?
