### ISSUE TITLE
Error python build

### ISSUE THREAD

**Issue by NguyenHaiAnh11** [deepmind/lab#178]
I'm trying to build the python module in an anaconda environment with:
`bazel build -c opt --python_version=PY3 //python/pip_package:build_pip_package`

however the build gets stuck at BUILD:902:1:

```
Linking of rule '//:libdmlab_headless_hw.so' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/libdmlab_headless_hw.so-2.params

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/ld.gold: error: cannot open /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libGL.so: No such file or directory
bazel-out/k8-opt/bin/external/lua_archive/_objs/lua/loslib.pic.o:loslib.c:function os_tmpname: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
collect2: error: ld returned 1 exit status
```
I've already installed `libffi-dev gettext freeglut3-dev libsdl2-dev libosmesa6-dev    libglu1-mesa libglu1-mesa-dev`. So i'm not sure what exactly is causing the problem. 

`WORKSPACE` has been modified to
```
new_local_repository(
    name = "sdl_system",
    build_file = "@//bazel:sdl.BUILD",
    path = "/usr",
)
new_local_repository(
    name = "python_system",
    build_file = "@//bazel:python.BUILD",
    path = "/home/haianh/anaconda3/envs/lab",
)
```
`python.BUILD` has been modified to
```
cc_library(
    name = "python",
    hdrs = select(
        {
            "@bazel_tools//tools/python:PY2": glob(["include/python2.7/*.h"]),
            "@bazel_tools//tools/python:PY3": glob([
            	"include/python3.6m/*.h",
            	"lib/python3.6/site-packages/numpy/core/include/numpy/*.h"]),
        },
        no_match_error = "Internal error, Python version should be one of PY2 or PY3",
    ),
    includes = select(
        {
            "@bazel_tools//tools/python:PY2": ["include/python2.7"],
            "@bazel_tools//tools/python:PY3": [
            	"include/python3.6m",
            	"lib/python3.6/site-packages/numpy/core/include"],
        },
        no_match_error = "Internal error, Python version should be one of PY2 or PY3",
    ),
    visibility = ["//visibility:public"],
)
```

**Comment by tkoeppe** [comment]
For the hardware OpenGL, you need something like GLX -- whatever it takes to make `-lGL` work!

**Comment by NguyenHaiAnh11** [comment]
Thank you @tkoeppe, apparently libGL.so points to libGL.so.1.0.0 which does not exist, while libGL.so.1.7.0 does. Hence recreating the symlink solved the problem. 

Why is it though that why I pip install the package, it also installs a new numpy (and six) version rather than using the one specified in the build file?

**Comment by tkoeppe** [comment]
> Why is it though that why I pip install the package, it also installs a new numpy (and six) version rather than using the one specified in the build file?

That's to some extent by design, and I do try to mention that in the "build instructions" documentation.  But there is no good answer: Our module's native code is built against Numpy headers, and those headers need to come from the same Numpy that you ultimately use at runtime. That's virtually impossible to solve with PIP dependencies: we want to compile the code ahead of time, for you, but you only decide much later which Numpy version you'll use.

Note that the Numpy version in the python.BUILD file is _under your control_, and something you're expected to edit to describe your actual platform. We do _not_ download and build Python and Numpy from source.

The enitre point of the PIP package is to use the module _outside_ the Bazel build system. But once you do that, you'll necessarily have to contend with mixing versions like that, and it is in some sense up to you to get that right.

I don't really understand how PIP expects native code dependencies to be used and declared; nor do I know what compatibility guarantees exist regarding native code (I expect it's something to do with semver?). If you have any suggestions, please let me know. I imagine we might want some sort of checked requirement that the Numpy version used to build the module is compatbile with all versions permitted by the PIP dependency requirement.

**Comment by tkoeppe** [comment]
Bear in mind also that we wanted the module to work in a hermetic context such as `virtualenv`, where your system's Numpy wouldn't be available. And the `six` dependency is just to make the example work.

I can see an argument why installing the dependencies should be optional. After all, if you already have Numpy and six on your system, and you're compiling against those, you may well want to use those, and not install separate Numpy packages. Maybe the requirements in `setup.py` should be moved into "extra" requirements, at the expense of users who do not want to concern themselves with *any* integration work (or maybe use the compiled binary on Docker or some other hermetic context). I don't have a good answer, but hopefully this illuminates the design space a little.

**Comment by tkoeppe** [comment]
I assume this issue is resolved now? Please reopen if not.

**Comment by NguyenHaiAnh11** [comment]
My bad, yeah I'm just trying to work around it now. Many thanks for your input!
