### ISSUE TITLE
any plan for lua environment api in near future?

### ISSUE THREAD

**Issue by pengsun** [deepmind/lab#29]
Hi,

Wondering if you have a plan for lua environment api like the one in `python` directory in near future?

**Comment by ElevenKong** [comment]
Thanks for your email, We have not any plan for lua environment api in near futur.来自孔祥亮的手机客户端手机：18969195737-------- 原始邮件 --------主题：[deepmind/lab] any plan for lua environment api in near future? (#29)发件人：pengsun 收件人：deepmind/lab 抄送：Subscribed Hi,
Wondering if you have a plan for lua environment api like the one in python directory in near future?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/deepmind/lab","title":"deepmind/lab","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/deepmind/lab"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"any plan for lua environment api in near future? (#29)"}],"action":{"name":"View Issue","url":"https://github.com/deepmind/lab/issues/29"}}}

**Comment by lefrana1** [comment]
At the moment, we do not have any plans to release a Lua environment API.

**Comment by tkoeppe** [comment]
We don't have a Lua API at the moment, and we don't plan to work on one at the moment, either. (It should, however, be fairly straight-forward to wrap the C API with Lua bindings.)
