### ISSUE TITLE
Compiling Errors regarding Lua and Python versions

### ISSUE THREAD

**Issue by spacelis** [deepmind/lab#5]
Hi,

It is a really interesting project. Thanks, DeepMind.

I just had some problems regarding the Lua and Python versions as well as linkage to zlib when compiling the code on Archlinux. The system default versions of Lua and Python are respectively 5.3 and 3.5, which are not support by current build files. My solution is to create a virtualenv of python27 and use the attached patch. Hopefully it will help someone. Thanks.
[archlinux-2016-12-07.patch.txt](https://github.com/deepmind/lab/files/636608/archlinux-2016-12-07.patch.txt)

**Comment by tkoeppe** [comment]
Thanks!

The changes for the Lua version look good. I'm hoping that the code would "just work" with Python 3, but we haven't tested that; we'd welcome patches that make the code Python version agnostic, if that's possible.

As for adding `-lz`, please see issue #2: I think it would be better to modify the linker script to expose the required symbols, since we do already link in our hermetic build of zlib.
